---
name: Python CI Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
      - name: install python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.11
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Build Package
        run: |
          pip install build
          python -m build
      - name: Run tests
        run: |
          pip install pytest
          pytest
      - name: upload a build artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: python-build
          path: staging
          
